import { ArrayKey } from "../../util/fun";

/** https://discord.com/developers/docs/topics/gateway#commands-and-events-gateway-events */
export const WSEvents = ArrayKey([
  "HELLO",
  "READY",
  "RESUMED",
  "RECONNECT",
  "INVALID_SESSION",
  "CHANNEL_CREATE",
  "CHANNEL_UPDATE",
  "CHANNEL_DELETE",
  "CHANNEL_PINS_UPDATE",
  "THREAD_CREATE",
  "THREAD_UPDATE",
  "THREAD_DELETE",
  "THREAD_LIST_SYNC",
  "THREAD_MEMBER_UPDATE",
  "THREAD_MEMBERS_UPDATE",
  "GUILD_CREATE",
  "GUILD_UPDATE",
  "GUILD_DELETE",
  "GUILD_BAN_ADD",
  "GUILD_BAN_REMOVE",
  "GUILD_EMOJIS_UPDATE",
  "GUILD_STICKERS_UPDATE",
  "GUILD_INTEGRATIONS_UPDATE",
  "GUILD_MEMBER_ADD",
  "GUILD_MEMBER_REMOVE",
  "GUILD_MEMBER_UPDATE",
  "GUILD_MEMBERS_CHUNK",
  "GUILD_ROLE_CREATE",
  "GUILD_ROLE_UPDATE",
  "GUILD_ROLE_DELETE",
  "INTEGRATION_CREATE",
  "INTEGRATION_UPDATE",
  "INTEGRATION_DELETE",
  "INTERACTION_CREATE",
  "INVITE_CREATE",
  "INVITE_DELETE",
  "MESSAGE_CREATE",
  "MESSAGE_UPDATE",
  "MESSAGE_DELETE",
  "MESSAGE_DELETE_BULK",
  "MESSAGE_REACTION_ADD",
  "MESSAGE_REACTION_REMOVE",
  "MESSAGE_REACTION_REMOVE_ALL",
  "MESSAGE_REACTION_REMOVE_EMOJI",
  "PRESENCE_UPDATE",
  "STAGE_INSTANCE_CREATE",
  "STAGE_INSTANCE_DELETE",
  "STAGE_INSTANCE_UPDATE",
  "TYPING_START",
  "USER_UPDATE",
  "VOICE_STATE_UPDATE",
  "VOICE_SERVER_UPDATE",
  "WEBHOOKS_UPDATE",
]);
export type WSEventType =
  | "READY"
  | "RESUMED"
  | "APPLICATION_COMMAND_CREATE"
  | "APPLICATION_COMMAND_DELETE"
  | "APPLICATION_COMMAND_UPDATE"
  | "GUILD_CREATE"
  | "GUILD_DELETE"
  | "GUILD_UPDATE"
  | "INVITE_CREATE"
  | "INVITE_DELETE"
  | "GUILD_MEMBER_ADD"
  | "GUILD_MEMBER_REMOVE"
  | "GUILD_MEMBER_UPDATE"
  | "GUILD_MEMBERS_CHUNK"
  | "GUILD_ROLE_CREATE"
  | "GUILD_ROLE_DELETE"
  | "GUILD_ROLE_UPDATE"
  | "GUILD_BAN_ADD"
  | "GUILD_BAN_REMOVE"
  | "GUILD_EMOJIS_UPDATE"
  | "GUILD_INTEGRATIONS_UPDATE"
  | "CHANNEL_CREATE"
  | "CHANNEL_DELETE"
  | "CHANNEL_UPDATE"
  | "CHANNEL_PINS_UPDATE"
  | "MESSAGE_CREATE"
  | "MESSAGE_DELETE"
  | "MESSAGE_UPDATE"
  | "MESSAGE_DELETE_BULK"
  | "MESSAGE_REACTION_ADD"
  | "MESSAGE_REACTION_REMOVE"
  | "MESSAGE_REACTION_REMOVE_ALL"
  | "MESSAGE_REACTION_REMOVE_EMOJI"
  | "THREAD_CREATE"
  | "THREAD_UPDATE"
  | "THREAD_DELETE"
  | "THREAD_LIST_SYNC"
  | "THREAD_MEMBER_UPDATE"
  | "THREAD_MEMBERS_UPDATE"
  | "USER_UPDATE"
  | "PRESENCE_UPDATE"
  | "TYPING_START"
  | "VOICE_STATE_UPDATE"
  | "VOICE_SERVER_UPDATE"
  | "WEBHOOKS_UPDATE"
  | "INTERACTION_CREATE"
  | "STAGE_INSTANCE_CREATE"
  | "STAGE_INSTANCE_UPDATE"
  | "STAGE_INSTANCE_DELETE"
  | "GUILD_STICKERS_UPDATE";

/** https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-close-event-codes */
export enum WsCodes {
  "未知錯誤" = 4000,
  "未知操作碼",
  "解碼錯誤",
  "未認證",
  "認證失敗",
  "通過身分認證",
  "無效 seq" = 4007,
  "限速",
  "超時",
  "無效分片",
  "需要分片",
  "API本版錯誤",
  "權限格式錯誤",
  "無權限",
}

/** https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-opcodes */
export enum OpCodes {
  DISPATCH = 0,
  HEARTBEAT,
  IDENTIFY,
  STATUS_UPDATE,
  VOICE_STATE_UPDATE,
  VOICE_GUILD_PING,
  RESUME,
  RECONNECT,
  REQUEST_GUILD_MEMBERS,
  INVALID_SESSION,
  HELLO,
  HEARTBEAT_ACK,
}

export default interface WsTypes {
  wsEvent: { [K in WSEventType]: K };
  Opcodes: { [K in OpCodes]: K };
  WsCodes: { [K in WsCodes]: K };
}
